Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm1_AGTCAA_L001_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm1_AGTCAA_L002_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm1_AGTCAA_L003_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm1_AGTCAA_L001_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm1_AGTCAA_L002_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm1_AGTCAA_L003_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm2_AGTTCC_L001_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm2_AGTTCC_L002_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm2_AGTTCC_L003_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm2_AGTTCC_L001_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm2_AGTTCC_L002_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm2_AGTTCC_L003_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm3_ATGTCA_L001_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm3_ATGTCA_L002_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm3_ATGTCA_L003_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm3_ATGTCA_L001_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm3_ATGTCA_L002_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tm3_ATGTCA_L003_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms1_GAGTGG_L001_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms1_GAGTGG_L002_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms1_GAGTGG_L003_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms1_GAGTGG_L001_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms1_GAGTGG_L002_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms1_GAGTGG_L003_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms2_ACTGAT_L001_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms2_ACTGAT_L002_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms2_ACTGAT_L003_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms2_ACTGAT_L001_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms2_ACTGAT_L002_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms2_ACTGAT_L003_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms3_ATTCCT_L001_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms3_ATTCCT_L002_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms3_ATTCCT_L003_R2_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms3_ATTCCT_L001_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms3_ATTCCT_L002_R1_001.fastq'
Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/python.git/count_total_uniq_fq_v2.py", line 15, in <module>
    with open(args.fq,'rb') as input_fq:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/trago/trago-tetraploids/Tms3_ATTCCT_L003_R1_001.fastq'
cat: *.csv: No such file or directory
tail: cannot open `*.csv' for reading: No such file or directory
